version: "3.9"
services:
  discord-bot:
    build: .
    ports:
      - "8000:8000" # Or any other port you want to expose for debugging/monitoring
    volumes:
      - .:/app # Mount the current directory to the /app directory inside the container
    depends_on:
      qdrant:
        condition: service_started
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Point to your external SearXNG instance - adjust the URL as needed
      - SEARXNG_URL=http://host.docker.internal:8888
      - SEARXNG_SECRET=9XnxlytPez_W5jwd9lkMt3ni1nouqfo6cYDQCiU-p6Q
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Makes host machine accessible from inside container

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

volumes:
  qdrant_storage:
